services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./src:/var/www/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build: ./php
    volumes:
      - ./src:/var/www/html/
    depends_on:
      - database
  database:
    image: "mysql:latest"
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: default_database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root